networks:
  frontend:
  backend:

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgres_data:

services:
  proxy:
    image: nginx
    volumes:
      - ./sonar.conf:/etc/nginx/conf.d/default.conf:ro
      - "/etc/sonar/ssl:/etc/sonar/ssl:ro"
      - "/var/log/sonar/nginx:/var/log/sonar/nginx"
    ports:
      - "443:443"
    restart: unless-stopped
    depends_on:
      - web
    networks:
      - frontend
  web:
    image: sonarqube:${SONAR_TAG:-community}
    hostname: sonarqube
    container_name: sonarqube
    read_only: true
    restart: unless-stopped
    labels:
      - autoheal=true
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=${SONAR_ES_BOOTSTRAP_CHECKS_DISABLE:-false}
      - SONAR_JDBC_URL=${SONAR_JDBC_URL:-jdbc:postgresql://db:5432/${POSTGRES_DB:-sonarqube}}
      - SONAR_JDBC_USERNAME=${POSTGRES_USER:-sonar}
      - SONAR_JDBC_PASSWORD=${POSTGRES_PASSWORD:-sonar}
      - SONAR_WEB_PORT=${SONAR_WEB_PORT:-9000}
    volumes:
      - "${SONAR_DATA:-sonarqube_data}:/opt/sonarqube/data"
      - "${SONAR_EXTS:-sonarqube_extensions}:/opt/sonarqube/extensions"
      - "${SONAR_LOGS:-sonarqube_logs}:/opt/sonarqube/logs"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - frontend
      - backend
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:13
    container_name: sonarqube_postgres
    restart: unless-stopped
    stop_grace_period: "3s"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-sonar}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sonar}
      POSTGRES_DB: ${POSTGRES_DB:-sonarqube}
    volumes:
      - "${PGDATA:-postgres_data}:/var/lib/postgresql/data"
    networks:
      - backend

  autoheal:
    image: willfarrell/autoheal:1.2.0
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      AUTOHEAL_CONTAINER_LABEL: autoheal
      AUTOHEAL_START_PERIOD: 600
      AUTOHEAL_INTERVAL: 30
